# Streamlit secrets for deployment
# Copy this to your Streamlit Cloud app secrets

KITE_API_KEY = "your_kite_api_key_here"
KITE_API_SECRET = "your_kite_api_secret_here" 
KITE_ACCESS_TOKEN = "your_access_token_here"
TELEGRAM_BOT_TOKEN = "your_telegram_bot_token_here"
TELEGRAM_CHAT_ID = "your_telegram_chat_id_here"
DRY_RUN = "true"
QTY_PER_TRADE = "10"
BUY_GAP_PERCENT = "2.0"
SELL_TARGET_PERCENT = "3.0"
LOSS_ALERT_PERCENT = "5.0"