# Streamlit Cloud Secrets Configuration
# Copy these EXACTLY to your Streamlit Cloud app secrets
# Go to: https://n8ncps-imny4jmu7twewjlglskjxh.streamlit.app/ → Manage app → Secrets

KITE_API_KEY = "i0bd6xlyqau3ivqe"
KITE_API_SECRET = "s2x3rpgijq921qmjgcerzqj3x6tkge6p"
KITE_ACCESS_TOKEN = "qz68Wy7GQ7kSvdxnxvQlwgCeWYmcTpvQ"
DRY_RUN = "false"