KITE_API_KEY = "i0bd6xlyqau3ivqe"
KITE_API_SECRET = "s2x3rpgijq921qmjgcerzqj3x6tkge6p"
KITE_ACCESS_TOKEN = "Oo3M2p45XpgNLLofiMVrNEDqTmE0Yo0F"
DRY_RUN = "false"
QTY_PER_TRADE = "10"
BUY_GAP_PERCENT = "2.0"
SELL_TARGET_PERCENT = "3.0"
LOSS_ALERT_PERCENT = "5.0"
WATCHLIST = "NIFTYBEES,UTISENSETF,INDA,MOM150ETF,MOM250ETF,ICICINXT50,SETFNIF100,KOTAKNIFTY200,ABSLNIFTY500ETF,MOMMICROETF,BANKBEES,ITBEES,PSUBANKBEES,PHARMABEES,FMCGBEES,ENERGYBEES,INFRAETF,AUTOETF,REALTYETF,MEDIAETF,PRBANKETF,METALETF,COMMODETF,SERVICESETF,CONSUMETF,DIVOPPBEES,GROWTHETF,MNCETF,GS813ETF,GS5YEARETF,CPSEETF,ICICIB22,MON100ETF,MOSP500ETF,MOEAFEETF,MOEMETF,ICICIESGETF,ALPHALVETF,QUALITYETF,VALUEETF,LOWVOLETF,EQUALWEIGHTETF,BHARATBONDETFAPR30,BHARATBONDETFAPR25,LIQUIDBEES,EDEL1DRATEETF,SBISDL26ETF,ICICISDL27ETF,HDFCGSEC30ETF,SILVERBEES,GOLDBEES,ICICIMID50,ICICISMALL100,ALPHA50ETF,EDELMOM30,ICICIHDIV,ICICIFINSERV,ICICIHEALTH,ICICIDIGITAL,ICICIMANUF"